优化

diff --git a/init.d/mysqld b/init.d/mysqld
--- a/init.d/mysqld
+++ b/init.d/mysqld
@@ -67,6 +67,31 @@ start()
     fi
 }
 
+skip-grant-tables-start()
+{
+    echo -n "Starting $NAME..."
+    if [ -f $PID_FILE ];then
+        mPID=`cat $PID_FILE`
+        isRunning=`ps ax | awk '{ print $1 }' | grep -e "^${mPID}$"`
+        if [ "$isRunning" != '' ];then
+            echo "$NAME (pid `pidof $NAME`) already running."
+            exit 1
+        fi
+    fi
+    $BIN --defaults-file=$CONFIG_FILE --skip-grant-tables >/dev/null 2>&1 &
+    if [ "$?" != 0 ] ; then
+        echo " failed"
+        exit 1
+    fi
+    wait_for_pid created $PID_FILE
+    if [ -n "$try" ] ; then
+        echo " failed"
+        exit 1
+    else
+        echo " done"
+    fi
+}
+
 stop()
 {
     echo -n "Stoping $NAME... "
@@ -131,9 +156,26 @@ status(){
     fi
 }
 
+set-root-password(){
+    $0 stop
+    $0 skip-grant-tables-start
+    $prefix/bin/mysql -uroot -S /tmp/mysql.sock <<EOF
+FLUSH PRIVILEGES;
+GRANT ALL PRIVILEGES ON *.* to root@'127.0.0.1' IDENTIFIED BY '$1';
+GRANT ALL PRIVILEGES ON *.* to root@'localhost' IDENTIFIED BY '$1';
+ALTER USER root@'127.0.0.1' IDENTIFIED WITH mysql_native_password BY '$1';
+ALTER USER root@'localhost' IDENTIFIED WITH mysql_native_password BY '$1';
+FLUSH PRIVILEGES;
+EOF
+    $0 restart
+}
+
 case "$1" in
     start)
         start
+        ;;
+    skip-grant-tables-start)
+        skip-grant-tables-start
         ;;
     stop)
         stop
@@ -147,6 +189,9 @@ case "$1" in
     reload)
         reload
         ;;
+    set-root-password)
+        set-root-password $2
+        ;;
     *)
-        echo $"Usage: $0 {start|stop|restart|reload|status}"
+        echo $"Usage: $0 {start|skip-grant-tables-start|stop|restart|reload|status|set-root-password}"
 esac
